import xbmc, xbmcaddon, xbmcgui, xbmcplugin,sys
import os
from resources.lib.comaddon import addon, dialog, xbmc, isKrypton, VSlog, addonManager, isMatrix
liste = []	
class sstreamer(xbmc.Player):
    ADDON = addon()    
    def __init__(self,name ,url):
                sPlayerType = self.__getPlayerType()
                xbmc.Player.__init__(self,sPlayerType)
                self.url=url
                self.name=name		
                self.layoutFinished()
              
    def layoutFinished(self):                                                                     
		
                liste.append((""+self.name, ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			          
                liste.append(("", ""+self.url))                                  
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))	                
                self.addLink('[COLOR lightblue][B]OTV MEDIA >>  [/B][/COLOR]' + self.name, self.url) 
 	        
    def addLink(self,name, url):
	        sUrl =(url)
	        sUrl1 =(url)
	        sUrl2 =(url)
	        sUrl3 =(url)
	        sUrl4 =(url)
	        sUrl5 =(url)
	        sUrl6 =(url)
	        sUrl7 =(url)
	     
   
	        playlist=xbmc.PlayList(xbmc.PLAYLIST_VIDEO); 
    
	        playlist.clear();
	        listitem1 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl,listitem1);
	        listitem2 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl1,listitem2);
	        listitem3 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl2,listitem3);
	        listitem4 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl3,listitem4);
	        listitem5 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl4,listitem5);                                                                         
	        listitem6 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl5,listitem6);
	        listitem7 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl6,listitem7);                                                                         
	        listitem8 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl7,listitem8);
	        
	        xbmcPlayer = xbmc.Player (); 
	        xbmcPlayer.play (playlist)  
	        sys.exit()
	        return ok 
    def __getPlayerType(self):
        sPlayerType = self.ADDON.getSetting('playerType')

        try:
            if (sPlayerType == '0'):
                #VSlog('playertype from config: auto')
                return xbmc.PLAYER_CORE_AUTO

            if (sPlayerType == '1'):
                #VSlog('playertype from config: mplayer')
                return xbmc.PLAYER_CORE_MPLAYER

            if (sPlayerType == '2'):
                #VSlog('playertype from config: dvdplayer')
                return xbmc.PLAYER_CORE_DVDPLAYER
        except:
            return False

          
            